/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import quotes.services.FileOperations;
import quotes.services.HttpOperations;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        FileOperations fileOperations = new FileOperations() ;
        HttpOperations httpOperations = new HttpOperations("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en" , "GET");

        if(httpOperations.startConnection().equals("success")) {
            Gson gsonObj = new Gson();
            ApiQuote reqQuote = gsonObj.fromJson(httpOperations.getData(), ApiQuote.class);
            fileOperations.insertDataInFile(reqQuote.getQuoteAuthor() , reqQuote.getQuoteText() , "app/src/main/resources/quotesFile.json");
            System.out.println("The author name : "+reqQuote.getQuoteAuthor());
            System.out.println("The quote : "+reqQuote.getQuoteText());
        }else {
            System.out.println(fileOperations.getQuote("app/src/main/resources/quotesFile.json"));
        }


    }


}





